# Generated by Django 4.2 on 2023-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1998-02-09'),
            preserve_default=False,
        ),
    ]
